### ISSUE TITLE
Is there a version of webpack-fast-refresh that supports webpack@4?

### ISSUE THREAD

**Issue by jayenashar** [WebHotelier/webpack-fast-refresh#1]
I see some comments and changelog that indicate there were versions that support webpack@4, but the README indicates that only webpack@5+ is supported.

**Comment by apostolos** [comment]
There was an effort to support both v4 & v5 at the same time, but since this fork's sole purpose is to provide a temporary solution for webpack@5 users, we now recommend webpack@4 users to use https://github.com/pmmmwh/react-refresh-webpack-plugin

All v4 related code has been removed.

We'll track and try to keep compatibility with the latest webpack beta(s) until the official release.

**Comment by jayenashar** [comment]
thank you!  i have created #2 for anyone else who may find your plugin but be using webpack@4.
